"""Convert japan.topojson (地球地図日本 via dataofjapan/land) into js/map-data.js.
Usage: python tools/build_map.py path/to/japan.topojson
"""
import json, math, sys

SRC = sys.argv[1]
OUT = 'js/map-data.js'
LAT0 = 36.0
K = 60.0            # px per degree latitude
COSL = math.cos(math.radians(LAT0))
LON_MIN, LAT_MAX = 128.2, 45.9
TOL = 0.9           # simplification tolerance (px)
MIN_AREA = 6.0      # drop islands smaller than this (px^2)
# Okinawa inset: shift so main islands sit in the Sea of Japan corner
OKI_DX, OKI_DY = (135.2 - 127.0), (43.2 - 26.6)
OKI_SCALE = 1.5

d = json.load(open(SRC, encoding='utf-8'))
sx, sy = d['transform']['scale']; tx, ty = d['transform']['translate']

def proj(lon, lat):
    return ((lon - LON_MIN) * COSL * K, (LAT_MAX - lat) * K)

def dp(pts, tol):
    if len(pts) < 3: return pts
    a, b = pts[0], pts[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]; L = math.hypot(dx, dy)
    best, idx = -1, 0
    for i in range(1, len(pts)-1):
        p = pts[i]
        dist = math.hypot(p[0]-a[0], p[1]-a[1]) if L == 0 else abs(dy*p[0]-dx*p[1]+b[0]*a[1]-b[1]*a[0]) / L
        if dist > best: best, idx = dist, i
    if best > tol:
        return dp(pts[:idx+1], tol)[:-1] + dp(pts[idx:], tol)
    return [a, b]

arcs = []
for a in d['arcs']:
    x = y = 0; pts = []
    for ddx, ddy in a:
        x += ddx; y += ddy; pts.append((x*sx+tx, y*sy+ty))
    arcs.append(pts)

def ring_ll(ring):
    out = []
    for i in ring:
        pts = arcs[i] if i >= 0 else arcs[~i][::-1]
        out.extend(pts if not out else pts[1:])
    return out

def area(r):
    return abs(sum(r[i][0]*r[i-1][1]-r[i-1][0]*r[i][1] for i in range(len(r)))) / 2

def keep_ring(pid, ll):
    lat = sum(p[1] for p in ll)/len(ll); lon = sum(p[0] for p in ll)/len(ll)
    if pid == 13 and lat < 34.0: return False          # Izu south / Ogasawara
    if pid == 46 and lat < 29.8: return False          # Tokara / Amami
    if pid == 47 and lon > 129.5: return False         # Daito islands
    return True

# simplify each arc once so shared borders stay seamless
proj_arcs = [dp([proj(*p) for p in a], TOL) for a in arcs]

def ring_xy(ring):
    out = []
    for i in ring:
        pts = proj_arcs[i] if i >= 0 else proj_arcs[~i][::-1]
        out.extend(pts if not out else pts[1:])
    return out

prefs = []
for g in d['objects']['japan']['geometries']:
    pid = g['properties']['id']
    polys = g['arcs'] if g['type'] == 'MultiPolygon' else [g['arcs']]
    parts = []; cx = cy = wsum = 0
    bx0 = by0 = 1e9; bx1 = by1 = -1e9
    for poly in polys:
        outer_ll = ring_ll(poly[0])
        if not keep_ring(pid, outer_ll): continue
        rings = []
        for k, ring in enumerate(poly):
            xy = ring_xy(ring)
            if pid == 47:
                ax, ay = proj(127.8 + OKI_DX, 26.4 + OKI_DY)
                xy = [(ax + (x + OKI_DX*COSL*K - ax) * OKI_SCALE, ay + (y - OKI_DY*K - ay) * OKI_SCALE) for x, y in xy]
            if len(xy) < 4 or area(xy) < MIN_AREA:
                if k == 0: break
                continue
            rings.append(xy)
        if not rings: continue
        a = area(rings[0])
        if a > wsum:  # label goes on the largest island
            cx = sum(p[0] for p in rings[0])/len(rings[0]); cy = sum(p[1] for p in rings[0])/len(rings[0]); wsum = a
        for x, y in rings[0]:
            bx0, by0, bx1, by1 = min(bx0, x), min(by0, y), max(bx1, x), max(by1, y)
        for r in rings:
            parts.append('M' + 'L'.join(f'{x:.1f},{y:.1f}' for x, y in r) + 'Z')
    prefs.append({'id': pid, 'd': ''.join(parts), 'cx': round(cx, 1), 'cy': round(cy, 1),
                  'bbox': [round(bx0, 1), round(by0, 1), round(bx1, 1), round(by1, 1)]})

prefs.sort(key=lambda p: p['id'])
W = max(p['bbox'][2] for p in prefs); H = max(p['bbox'][3] for p in prefs)
oki = next(p for p in prefs if p['id'] == 47)['bbox']
with open(OUT, 'w', encoding='utf-8') as f:
    f.write('// @ts-check\n// AUTO-GENERATED by tools/build_map.py — do not edit by hand.\n')
    f.write('// 出典: 地球地図日本 (国土地理院) — https://www.gsi.go.jp/kankyochiri/gm_jpn.html\n\n')
    f.write('/** @typedef {{id:number,d:string,cx:number,cy:number,bbox:[number,number,number,number]}} PrefShape */\n\n')
    f.write(f'export const MAP_SIZE = {{ width: {math.ceil(W)+10}, height: {math.ceil(H)+10} }};\n')
    f.write(f'/** Okinawa inset frame */\nexport const OKINAWA_BOX = {json.dumps([round(oki[0]-14,1), round(oki[1]-14,1), round(oki[2]+14,1), round(oki[3]+14,1)])};\n\n')
    f.write('/** @type {PrefShape[]} */\nexport const PREF_SHAPES = ' + json.dumps(prefs, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('ok', W, H, oki, sum(len(p['d']) for p in prefs))
